// Shared copy for shop / driver lead-capture banners and registration pages.
export const REGISTRATION_TYPES = {
  shop: {
    path: '/register/shop',
    gradient: 'from-brand-dark via-brand to-brand-dark',
    bgImage: '/shop-banner-bg.jpg',
    bgPosition: 'center bottom',
    icon: '🛒',
    badge: 'خوشخبری!',
    title: 'اپنی دکان کو آن لائن کریں',
    subtitle: 'نارنگ منڈی سمیت پورے پاکستان سے کسٹمرز تک رسائی حاصل کریں',
    perks: ['زیادہ کسٹمرز، زیادہ سیلز', 'پورے پاکستان میں رسائی', 'کاروبار کی مفت پروموشن'],
    cta: 'آج ہی رجسٹر کریں',
    pageTitle: 'دکان رجسٹر کریں',
    seoTitle: 'دکان رجسٹریشن',
    seoDescription: 'اپنی دکان کو نارنگ منڈی پر آن لائن رجسٹر کریں — پورے پاکستان سے کسٹمرز تک رسائی۔',
    businessLabel: 'دکان کا نام',
    businessPlaceholder: 'دکان کا نام',
    imageLabel: 'دکان کی تصویر',
  },
  driver: {
    path: '/register/driver',
    gradient: 'from-gray-900 via-brand-dark to-black',
    bgImage: '/driver-banner-bg.jpg',
    bgPosition: 'center',
    icon: '🚕',
    badge: 'ڈرائیور حضرات کے لیے خوشخبری!',
    title: 'بطور ڈرائیور ابھی خود کو رجسٹر کریں',
    subtitle: 'زیادہ آرڈرز، زیادہ آمدن — محفوظ اور بہترین سروس',
    perks: ['زیادہ آرڈرز، زیادہ آمدن', 'گھر بیٹھے بکنگ حاصل کریں', 'بذریعہ واٹس ایپ آسان بکنگ'],
    cta: 'ابھی رجسٹر کریں',
    pageTitle: 'ڈرائیور رجسٹریشن',
    seoTitle: 'ڈرائیور رجسٹریشن',
    seoDescription: 'نارنگ منڈی پر بطور ڈرائیور رجسٹر کریں — زیادہ آرڈرز، زیادہ آمدن، آسان واٹس ایپ بکنگ۔',
    businessLabel: 'گاڑی کا نام / نمبر',
    businessPlaceholder: 'مثلاً: کرولا — LEB 1234',
    imageLabel: 'گاڑی کی تصویر',
  },
};
